service: user-service

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  stage: dev
  environment:
    SNS_TOPIC_ARN: !Ref SNSTopic
    SQS_PE_URL: !Ref SQSPE
    SQS_CL_URL: !Ref SQSCL
    EVENT_BUS_NAME: !Ref EventBridgeBus
    CONFIRM_SQS_URL: !Ref ConfirmSQS
    APPOINTMENT_TABLE: Appointments
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - sns:*
        - sqs:*
        - events:*
      Resource: "*"

functions:
  appointment:
    handler: dist/src/infrastructure/api/handlers/appointmentHandler.handler
    events:
      - httpApi:
          path: /appointments
          method: POST
      - httpApi:
          path: /appointments/{insuredId}
          method: GET

  appointment_pe:
    handler: dist/src/infrastructure/api/handlers/appointmentPEHandler.handler
    events:
      - sqs:
          arn: !GetAtt SQSPE.Arn

  appointment_cl:
    handler: dist/src/infrastructure/api/handlers/appointmentCLHandler.handler
    events:
      - sqs:
          arn: !GetAtt SQSCL.Arn

  appointment_confirm:
    handler: dist/src/infrastructure/api/handlers/appointmentStatusHandler.handler
    events:
      - sqs:
          arn: !GetAtt ConfirmSQS.Arn

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true

resources:
  Resources:

    # 🔥 DynamoDB
    AppointmentsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Appointments
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: insuredId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: insuredId-index
            KeySchema:
              - AttributeName: insuredId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # 🔥 SNS + SQS
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SNSTopic

    SQSPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_PE

    SQSCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_CL

    SQSPEPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSPE
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "sqs:SendMessage"
              Resource: !GetAtt SQSPE.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref SNSTopic

    SQSCLPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSCL
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "sqs:SendMessage"
              Resource: !GetAtt SQSCL.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref SNSTopic

    SNSTopicToSQSPE:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref SNSTopic
        Protocol: sqs
        Endpoint: !GetAtt SQSPE.Arn
        FilterPolicy:
          countryISO:
            - PE

    SNSTopicToSQSCL:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref SNSTopic
        Protocol: sqs
        Endpoint: !GetAtt SQSCL.Arn
        FilterPolicy:
          countryISO:
            - CL

    # 🔥 EventBridge y Confirmación
    EventBridgeBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: AppointmentEventBus

    EventBridgeToSQSTargetRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EventBridgeToSQSRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AllowSQSSend
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: sqs:SendMessage
                  Resource: !GetAtt ConfirmSQS.Arn

    EventBridgeToSQS:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: !Ref EventBridgeBus
        EventPattern:
          source:
            - user-service
          detail-type:
            - CustomEvent
        Targets:
          - Arn: !GetAtt ConfirmSQS.Arn
            Id: "TargetSQS"
            RoleArn: !GetAtt EventBridgeToSQSTargetRole.Arn

    ConfirmSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ConfirmSQS

outputs:
  SNSTopicArn:
    Value: !Ref SNSTopic
  SQSPEUrl:
    Value: !Ref SQSPE
  SQSCLUrl:
    Value: !Ref SQSCL
  EventBridgeBusName:
    Value: !Ref EventBridgeBus
  ConfirmSQSUrl:
    Value: !Ref ConfirmSQS